services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true